=== ricardobranco/el1314/PED/TPs/TP2-SIP-XSLT/SIP.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT sip (meta, abstract, files) >

<!ELEMENT meta (keyname, title, subtitle?, course, class, sdate, edate?,
                supervisors, workteam) >

<!ELEMENT keyname (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT subtitle (#PCDATA) >
<!ELEMENT course (#PCDATA) >
<!ELEMENT class (#PCDATA) >
<!ELEMENT sdate (#PCDATA) >
<!ELEMENT edate (#PCDATA) >

<!ELEMENT supervisors (supervisor)+ >
<!ELEMENT supervisor (name, email, webpage?) >

<!ELEMENT name (#PCDATA) >
<!ELEMENT email (#PCDATA) >
<!ELEMENT webpage (#PCDATA) >

<!ELEMENT workteam (member)+ >
<!ELEMENT member (name, id, email, webpage?, photo?) >

<!ELEMENT photo (#PCDATA) >
<!ELEMENT id (#PCDATA) >

<!ELEMENT abstract (p)+ >

<!ELEMENT p (#PCDATA|i|u|b|acr|xref)* >

<!ELEMENT i (#PCDATA|u|b)* >
<!ELEMENT u (#PCDATA|i|b)* >
<!ELEMENT b (#PCDATA|u|i)* >

<!ELEMENT acr (abv, desc) >
<!ELEMENT abv (#PCDATA) >
<!ELEMENT desc (#PCDATA) >

<!ELEMENT xref (#PCDATA) >

<!ATTLIST xref
    uri CDATA #REQUIRED>
    
<!ELEMENT files (file)+ >
<!ELEMENT file (#PCDATA) >
<!ATTLIST file
    path CDATA #REQUIRED
    format CDATA #IMPLIED
    checksum CDATA #IMPLIED>

=== ricardobranco/el1314/PED/TPs/TP6-SupervisionForm/SIP.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sip SYSTEM "SIP.dtd">
<sip>
    <meta>
        <keyname>EL::PED::TP6</keyname>
        <title>TP 6 - Formulário de Supervisões</title>
        <subtitle>Sexto projecto para avaliação</subtitle>
        <course>MEI</course>
        <class>EL</class>
        <sdate>2013-11-18</sdate>
        <edate>2013-11-24</edate>
        <supervisors>
            <supervisor>
                <name>José Carlos Ramalho</name>
                <email>jcr@di.uminho.pt</email>
                <webpage>http://www.di.uminho.pt/~jcr</webpage>
            </supervisor>
        </supervisors>
        <workteam>
            <member>
                <name>André Augusto Costa Santos</name>
                <id>PG25329</id>
                <email>andreccdr@gmail.com</email>
                <webpage>http://andre-santos.pt</webpage>
                <photo>img/andre.jpg</photo>
            </member>
            <member>
                <name>Daniel Alberto Pinto Carvalho</name>
                <id>A61008</id>
                <email>edu@danielcarvalho.pt</email>
                <webpage>http://danielcarvalho.pt</webpage>
                <photo>img/daniel.jpg</photo>
            </member>
            <member>
                <name>Ricardo Jorge Rodrigues Branco</name>
                <id>PG25339</id>
                <email>28.ricardobranco@gmail.com</email>
                <photo>img/ricardo.jpg</photo>
            </member>
        </workteam>
    </meta>
    <abstract>
        <p>Neste projecto é criado um formulário para inserção e listagens de supervisões e armazenando a informação num de ficheiro eXtensible Markup Language.
        </p>
    </abstract>
    <files>
        <file path="SIP.xml" format="XML">
            Project Record em XML
        </file>
        <file path="listing.php" format="PHP">
            Ficheiro PHP para listagem de supervisoões
        </file>
        <file path="supervisions.php" format="PHP">
            Ficheiro PHP para tratamento do formulário
        </file>
        <file path="index.php" format="PHP">
            Formulário de Supervisões
        </file>
        <file path="assets/style.css" format="CSS">
            Stylesheet para formulário
        </file>
        <file path="assets/custom.css" format="CSS">
            Overrrides para Stylesheet do formulário
        </file>
        <file path="assets/functions.js" format="CSS">
            Javascript para formulário
        </file>
        <file path="assets/jquery.js" format="CSS">
            Jquery
        </file>

    </files>
</sip>

=== ricardobranco/el1314/PED/TPs/TP2-SIP-XSLT/SIP.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sip SYSTEM "SIP.dtd">
<sip>
    <meta>
        <keyname>EL::PED::SIP.XSLT</keyname>
        <title>TPC 2 - EXtensible Stylesheet Language Transformations para Submission Information Package</title>
        <subtitle>Segundo projecto para avaliação</subtitle>
        <course>MEI</course>
        <class>EL</class>
        <sdate>2013-10-14</sdate>
        <edate>2013-10-21</edate>
        <supervisors>
            <supervisor>
                <name>José Carlos Ramalho</name>
                <email>jcr@di.uminho.pt</email>
                <webpage>http://www.di.uminho.pt/~jcr</webpage>
            </supervisor>
        </supervisors>
        <workteam>
            <member>
                <name>André Augusto Costa Santos</name>
                <id>PG25329</id>
                <email>andreccdr@gmail.com</email>
                <webpage>http://andre-santos.pt</webpage>
                <photo>andre.jpg</photo>
            </member>
            <member>
                <name>Daniel Alberto Pinto Carvalho</name>
                <id>A61008</id>
                <email>edu@danielcarvalho.pt</email>
                <webpage>http://danielcarvalho.pt</webpage>
                <photo>daniel.jpg</photo>
            </member>
            <member>
                <name>Ricardo Jorge Rodrigues Branco</name>
                <id>PG25339</id>
                <email>28.ricardobranco@gmail.com</email>
                <photo>ricardo.jpg</photo>
            </member>
        </workteam>
    </meta>
    <abstract>
        <p>
            Neste projecto foram desenvolvidas 
            <acr>
                <abv>XSLT</abv> 
                <desc>EXtensible Stylesheet Language Transformations</desc>
            </acr>    
            para um 
            <acr>
                <abv>SIP</abv>
                <desc>Submission Information Package</desc>
            </acr>.
        </p>
        <p>
            <b>XSL</b> ou <b><i>EXtensible Sytlesheet Language</i></b> 
            é uma linguagem que permite desenvolver transformações 
            (<acr>
                <abv>XSLT</abv> 
                <desc>EXtensible Stylesheet Language Transformations</desc>
            </acr>) 
            para ficheiros 
            <acr>
                <abv>XML</abv>
                <desc>Extensible Markup Language</desc>
            </acr>
            que nos permita transformá-los de forma a obter outros 
            <acr>
                <abv>XML</abv>
                <desc>Extensible Markup Language</desc>
            </acr>
            ou outros objectos tais como páginas
            <acr>
                <abv>HTML</abv>
                <desc>HyperText Markup Language</desc>
            </acr>
            como é o caso deste projecto.
        </p>
        <p>
            Para além das 
            <acr>
                <abv>XSLT</abv> 
                <desc>EXtensible Stylesheet Language Transformations</desc>
            </acr>
            já referidas, este projecto contempla ainda uma <b><i>Document Type Definition</i></b>, 
            ou simplesmente <b>DTD</b>, 
            assim como um 
            <acr>
                <abv>XML</abv>
                <desc>Extensible Markup Language</desc>
            </acr>
            onde se aplicam as regras da mesma e que é usado como base deste relatório.
        </p>
        <p>
            De forma a tornar a experiência mais agradável na visualização do resultado das 
            <acr>
                <abv>XSLT</abv> 
                <desc>EXtensible Stylesheet Language Transformations</desc>
            </acr>
            foram também inseridas no projecto regras de estilo, através de 
            <acr>
                <abv>CSS</abv> 
                <desc>Cascading Style Sheets</desc>
            </acr>, 
            assim como as fotografias dos membros do grupo de trabalho.
        </p>
        
    </abstract>
    <files>
        <file path="SIP.dtd" format="DTD" checksum="e64a5965c36937a27ada11030f7d3183">
            Document Type Definition
        </file>
        <file path="SIP.xml" format="XML">
            Project Record
        </file>
        <file path="SIP.xsl" format="XSL">
            EXtensible Stylesheet Language Transformations
        </file>
        <file path="SIP.html" format="HTML">
            HyperText Markup
        </file>
        <file path="style.css" format="CSS">
            Cascading Style Sheet
        </file>
        <file path="andre.jpg" format="JPG">
            Workteam member photo: Andre Santos
        </file>
        <file path="daniel.jpg" format="JPG">
            Workteam member photo: Daniel Carvalho
        </file>
        <file path="ricardo.jpg" format="JPG">
            Workteam member photo: Ricardo Branco
        </file>
    </files>
</sip>

=== ricardobranco/el1314/PED/TPs/TP7-XSLT-Schema/SIP.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sip SYSTEM "SIP.dtd">
<sip>
    <meta>
        <keyname>EL::PED::TP6</keyname>
        <title>TP 6 - Formulário de Supervisões</title>
        <subtitle>Sexto projecto para avaliação</subtitle>
        <course>MEI</course>
        <class>EL</class>
        <sdate>2013-11-25</sdate>
        <edate>2013-12-02</edate>
        <supervisors>
            <supervisor>
                <name>José Carlos Ramalho</name>
                <email>jcr@di.uminho.pt</email>
                <webpage>http://www.di.uminho.pt/~jcr</webpage>
            </supervisor>
        </supervisors>
        <workteam>
            <member>
                <name>André Augusto Costa Santos</name>
                <id>PG25329</id>
                <email>andreccdr@gmail.com</email>
                <webpage>http://andre-santos.pt</webpage>
                <photo>img/andre.jpg</photo>
            </member>
            <member>
                <name>Daniel Alberto Pinto Carvalho</name>
                <id>A61008</id>
                <email>edu@danielcarvalho.pt</email>
                <webpage>http://danielcarvalho.pt</webpage>
                <photo>img/daniel.jpg</photo>
            </member>
            <member>
                <name>Ricardo Jorge Rodrigues Branco</name>
                <id>PG25339</id>
                <email>28.ricardobranco@gmail.com</email>
                <photo>img/ricardo.jpg</photo>
            </member>
        </workteam>
    </meta>
    <abstract>
        <p>Neste projecto é criado um formulário através de XSLT, a partir de um Schema
        </p>
    </abstract>
    <files>
        <file path="SIP.xml" format="XML">
            Project Record em XML
        </file>
        <file path="add-supervision.php" format="PHP">
            Ficheiro PHP adicionar supervisões
        </file>
       <file path="skeleton.xsl" format="XSL">
            Conversor de Schema num formulario HTML
        </file>
        <file path="thesup.xsl" format="XSD">
            Schema
        </file>
        
        <file path="assets/style.css" format="CSS">
            Stylesheet para formulário
        </file>
        <file path="assets/custom.css" format="CSS">
            Overrrides para Stylesheet do formulário
        </file>
        <file path="assets/functions.js" format="JS">
            Javascript para formulário
        </file>
        <file path="assets/jquery.js" format="JS">
            Jquery
        </file>

    </files>
</sip>

=== ricardobranco/el1314/PED/TPs/TP8-SQL-Juris/manifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sip SYSTEM "SIP.dtd">
<sip>
    <meta>
        <keyname>EL::PED::TP8</keyname>
        <title>TP 8 - SQL para adicionar informação dos júris a uma base de dados SQL</title>
        <subtitle>Oitavo projecto para avaliação</subtitle>
        <course>MEI</course>
        <class>EL</class>
        <sdate>2013-12-02</sdate>
        <edate>2013-12-09</edate>
        <supervisors>
            <supervisor>
                <name>José Carlos Ramalho</name>
                <email>jcr@di.uminho.pt</email>
                <webpage>http://www.di.uminho.pt/~jcr</webpage>
            </supervisor>
        </supervisors>
        <workteam>
            <member>
                <name>André Augusto Costa Santos</name>
                <id>PG25329</id>
                <email>andreccdr@gmail.com</email>
                <webpage>http://andre-santos.pt</webpage>
                <photo>img/andre.jpg</photo>
            </member>
            <member>
                <name>Daniel Alberto Pinto Carvalho</name>
                <id>A61008</id>
                <email>edu@danielcarvalho.pt</email>
                <webpage>http://danielcarvalho.pt</webpage>
                <photo>img/daniel.jpg</photo>
            </member>
            <member>
                <name>Ricardo Jorge Rodrigues Branco</name>
                <id>PG25339</id>
                <email>28.ricardobranco@gmail.com</email>
                <photo>img/ricardo.jpg</photo>
            </member>
        </workteam>
    </meta>
    <abstract>
        <p>Neste trabalho com um XSLT aplicado ao Schema dos júris são geradas as queries para a criação das tabelas da base de dados.</p>
        <p>Depois com um script de PHP são gerados os inserts a partir do ficheiro XML com informação dos júris.</p>        
        <p>De notar que a base de dados foi construida na 3º forma normal, o que dificultou a criação de um XSLT genérico</p>
    </abstract>
    <files>
        <file path="create_tables_vGenerica.sql" format="SQL">
            Ficheiro SQL para criação das tabelas, utilizando o XSLT mais genérico
        </file>
        <file path="create_tables_vGenerica.xsl" format="XSL">
            Ficheiro XSLT mais genérico ( Instituições na tabela dos Júris )
        </file>
        <file path="create_tables.sql" format="SQL">
            Ficheiro SQL utilizado para a criação das tabelas
        </file>
        <file path="create_tables.xsl" format="XSL">
            Ficheiro XSLT utilizado para gerar o SQL de criação das tabelas
        </file>
        <file path="database.db" format="SQLite3">
            Base de Dados SQLite Final
        </file>
        <file path="geraSQL.php" format="PHP">
            Script em PHP responável por gerar o ficheiro SQL com inserts.
        </file>
        <file path="the-exams.xsd" format="XSD">
            Schema Júris
        </file>
        <file path="the-exam.xsd" format="XSD">
            Schema Júri
        </file>
        <file path="inserts.sql" format="SQL">
            Ficheiro SQL com inserts.
        </file>
        <file path="the-exams.xml" format="XML">
            Ficheiro XML com informação dos Júris.
        </file>
    </files>
</sip>

=== ricardobranco/el1314/PED/TPs/TP3-MapaCidades/SIP.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sip SYSTEM "SIP.dtd">
<sip>
    <meta>
        <keyname>EL::PED::TP3</keyname>
        <title>TP 3 - Mapa de Cidades</title>
        <subtitle>Terceiro projecto para avaliação</subtitle>
        <course>MEI</course>
        <class>EL</class>
        <sdate>2013-10-28</sdate>
        <edate>2013-11-04</edate>
        <supervisors>
            <supervisor>
                <name>José Carlos Ramalho</name>
                <email>jcr@di.uminho.pt</email>
                <webpage>http://www.di.uminho.pt/~jcr</webpage>
            </supervisor>
        </supervisors>
        <workteam>
            <member>
                <name>André Augusto Costa Santos</name>
                <id>PG25329</id>
                <email>andreccdr@gmail.com</email>
                <webpage>http://andre-santos.pt</webpage>
                <photo>img/andre.jpg</photo>
            </member>
            <member>
                <name>Daniel Alberto Pinto Carvalho</name>
                <id>A61008</id>
                <email>edu@danielcarvalho.pt</email>
                <webpage>http://danielcarvalho.pt</webpage>
                <photo>img/daniel.jpg</photo>
            </member>
            <member>
                <name>Ricardo Jorge Rodrigues Branco</name>
                <id>PG25339</id>
                <email>28.ricardobranco@gmail.com</email>
                <photo>img/ricardo.jpg</photo>
            </member>
        </workteam>
    </meta>
    <abstract>
        <p>Neste projecto foi desenvolvido uma <acr>
            <abv>XSLT</abv>
            <desc>eXtensible Stylesheet Language for Transformation</desc>
        </acr> para representar um documento <acr>
            <abv>XML</abv>
            <desc>eXtensible Markup Language</desc>
        </acr>, com informação relativa a cidades e às suas ligações, num <i>website</i> em <acr>
            <abv>HTML</abv>
            <desc>HyperText Markup Language</desc>
        </acr>.</p>
        
        <p>Como resultado do projecto, podemos encontrar uma página 
            <xref uri="mapa/index.html">Index.html</xref> com o índice de cidades, e depois uma página para cada cidade identificada com o <b>ID</b>.</p>
        <p>Na página de cada cidade é apresentada informação relativa ao Nome, Descrição, Ligações Diretas e Ligações inversas.</p>
    </abstract>
    <files>
        <file path="SIP.xml" format="XML">
            Project Record em XML
        </file>
        <file path="SIP.html" format="HTML">
            Project Record em HTML
        </file>
        <file path="css/style.css" format="CSS">
            Ficheiro de estilo
        </file>
        <file path="mapa/index.html" format="HTML">
            Índice de Cidades
        </file>
        <file path="mapa/brg.html" format="HTML">
            Página de Braga
        </file>
        <file path="mapa/bcl.html" format="HTML">
            Página de Barcelos
        </file>
        <file path="mapa/ptl.html" format="HTML">
            Página de Ponte de Lima
        </file>
        <file path="mapa/gmr.html" format="HTML">
            Página de Guimarães
        </file>
        <file path="mapa/fml.html" format="HTML">
            Página de Famalicão
        </file>
        <file path="mapa/prt.html" format="HTML">
            Página do Porto
        </file>
        <file path="mapa/vct.html" format="HTML">
            Página de Viana do Castelo
        </file>
        <file path="img/andre.jpg" format="JPG">
            Workteam member photo: Andre Santos
        </file>
        <file path="img/daniel.jpg" format="JPG">
            Workteam member photo: Daniel Carvalho
        </file>
        <file path="img/ricardo.jpg" format="JPG">
            Workteam member photo: Ricardo Branco
        </file>
    </files>
</sip>

=== ricardobranco/el1314/PED/TPs/TP4-FormSip/SIP.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sip SYSTEM "SIP.dtd">
<sip>
    <meta>
        <keyname>EL::PED::TP4</keyname>
        <title>TP 4 - Formulário para SIP</title>
        <subtitle>Quarto projecto para avaliação</subtitle>
        <course>MEI</course>
        <class>EL</class>
        <sdate>2013-11-04</sdate>
        <edate>2013-11-11</edate>
        <supervisors>
            <supervisor>
                <name>José Carlos Ramalho</name>
                <email>jcr@di.uminho.pt</email>
                <webpage>http://www.di.uminho.pt/~jcr</webpage>
            </supervisor>
        </supervisors>
        <workteam>
            <member>
                <name>André Augusto Costa Santos</name>
                <id>PG25329</id>
                <email>andreccdr@gmail.com</email>
                <webpage>http://andre-santos.pt</webpage>
                <photo>img/andre.jpg</photo>
            </member>
            <member>
                <name>Daniel Alberto Pinto Carvalho</name>
                <id>A61008</id>
                <email>edu@danielcarvalho.pt</email>
                <webpage>http://danielcarvalho.pt</webpage>
                <photo>img/daniel.jpg</photo>
            </member>
            <member>
                <name>Ricardo Jorge Rodrigues Branco</name>
                <id>PG25339</id>
                <email>28.ricardobranco@gmail.com</email>
                <photo>img/ricardo.jpg</photo>
            </member>
        </workteam>
    </meta>
    <abstract>
        <p>Neste projecto foi desenvolvido um formulário para  <acr>
            <abv>SIP</abv>
            <desc>Submission Information Package</desc>
        </acr> que gera um ficheiro <acr>
            <abv>HTML</abv>
            <desc>HyperText Markup Language</desc>
        </acr> com os dados do formulário
        juntamente com os ficheiros que foram enviados também pelo formulário, recorrendo à linguagem
        <acr>
            <abv>PHP</abv>
            <desc>Hypertext Preprocessor</desc>
        </acr>.
    </p>
    </abstract>
    <files>
        <file path="SIP.xml" format="XML">
            Project Record em XML
        </file>
        <file path="SIP.dtd" format="DTD">
            Document Type Definition
        </file>
        <file path="Index.html" format="HTML">
            Formulário para SIP
        </file>
        <file path="form.php" format="PHP">
            Script parar formulário do SIP
        </file>
        <file path="assets/style.css" format="CSS">
            Stylesheet para formulário
        </file>
        <file path="assets/custom.css" format="CSS">
            Overrrides para Stylesheet do formulário
        </file>
        <file path="assets/functions.js" format="CSS">
            Javascript para formulário
        </file>
        <file path="assets/jquery.js" format="CSS">
            Jquery
        </file>

    </files>
</sip>

=== ricardobranco/el1314/PED/TPs/TP2_5-TPS/SIP.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sip SYSTEM "SIP.dtd">
<sip>
    <meta>
        <keyname>EL::PED::SIP.XSLT</keyname>
        <title>TPC 3 - EXtensible Stylesheet Language Transformations para Indices de Grupos de trabalho</title>
        <subtitle>Terceiro projecto para avaliação</subtitle>
        <course>MEI</course>
        <class>EL</class>
        <sdate>2013-10-21</sdate>
        <edate>2013-10-27</edate>
        <supervisors>
            <supervisor>
                <name>José Carlos Ramalho</name>
                <email>jcr@di.uminho.pt</email>
                <webpage>http://www.di.uminho.pt/~jcr</webpage>
            </supervisor>
        </supervisors>
        <workteam>
            <member>
                <name>André Augusto Costa Santos</name>
                <id>PG25329</id>
                <email>andreccdr@gmail.com</email>
                <webpage>http://andre-santos.pt</webpage>
                <photo>andre.jpg</photo>
            </member>
            <member>
                <name>Daniel Alberto Pinto Carvalho</name>
                <id>A61008</id>
                <email>edu@danielcarvalho.pt</email>
                <webpage>http://danielcarvalho.pt</webpage>
                <photo>daniel.jpg</photo>
            </member>
            <member>
                <name>Ricardo Jorge Rodrigues Branco</name>
                <id>PG25339</id>
                <email>28.ricardobranco@gmail.com</email>
                <photo>ricardo.jpg</photo>
            </member>
        </workteam>
    </meta>
    <abstract>
        <p>
            Neste projecto foram desenvolvidas 
            <acr>
                <abv>XSLT</abv> 
                <desc>EXtensible Stylesheet Language Transformations</desc>
            </acr>    
            de forma a criar um índice de grupos.
        </p>
    </abstract>
    <files>
        <file path="SIP.xml" format="XML">
            Project Record
        </file>
        <file path="TPS.dtd" format="DTD">
            Document Type Definition para Índice de Grupos
        </file>
        <file path="TPS.xml" format="XML">
            Extensible Markup Language para Índice de Grupos
        </file>
        <file path="TPS.xls" format="XLS">
            EXtensible Stylesheet Language Transformations para Índice de Grupos
        </file>
        <file path="TPS.html" format="HTML">
            HyperText Markup Language para Índice de Grupos
        </file>
        <file path="style.css" format="CSS">
            Cascading Style Sheet para Índice de Grupos
        </file>
    </files>
</sip>
